

host: https://m.lechebang.cn/gateway/

excel:
  file: cases01.xlsx

logger:
  name: ""
  file: "response日志.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"


db:
  host: 'saas-mysql.lcbtest.cn'
  port: 3306
  user: 'lcb_dev'
  password: '@,ue"L&5WylnK$GRb&ms'
  charset: 'utf8'
  cursorclass: DictCursor


user:
  appCode: 1011
  code: 1111
  mobile: 13800000000


admin_user:
  passwd: buzhidao888
  loginName: 13013082657